nomÂ : DÃ©mo des actions GitHub
run-nameÂ : ${{ github.actor }} teste les actions GitHub ğŸš€
sur : [pousser]
emplois:
  Explorer-GitHub-ActionsÂ :
    fonctionne sur : ubuntu-latest
    mesures:
      - run : echo "ğŸ‰ Le travail a Ã©tÃ© automatiquement dÃ©clenchÃ© par un Ã©vÃ©nement ${{ github.event_name }}."
      - run : echo "ğŸ§ Ce travail est maintenant en cours d'exÃ©cution sur un serveur ${{ runner.os }} hÃ©bergÃ© par GitHub !"
      - run : echo "ğŸ” Le nom de votre branche est ${{ github.ref }} et votre dÃ©pÃ´t est ${{ github.repository }}."
      - nomÂ :Â Consulter le code du rÃ©fÃ©rentiel
        utilisations : actions/checkout@v4
      - run : echo "ğŸ’¡ Le dÃ©pÃ´t ${{ github.repository }} a Ã©tÃ© clonÃ© sur le runner."
      - run : echo "ğŸ–¥ï¸ Le workflow est maintenant prÃªt Ã  tester votre code sur le runner."
      - nom : liste des fichiers dans le rÃ©fÃ©rentiel
        courir: |
          ls ${{ github.espace de travail }}
      - run : echo "ğŸ Le statut de ce travail est ${{ job.status }}."
